name: asset_plus
description: An UI assignment for Asset_Plus

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  http:
  google_fonts:
  provider:
  json_serializable:
  flutter:
    sdk: flutter



  cupertino_icons:

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true
